# Discipline tracks for the Clinical Academy. ONE 10-minute module per discipline:
#   learning <= 6 min  (2-min lessons, plus a 2-min visual map where a scene exists)
#   checks   <= 4 min  (one per lesson, then "Check yourself" to make four)
# The builder enforces both caps.
# Lesson = (title, [paragraphs], [key points], stem, [A, B, C, D], answer, feedback)
# Check  = (stem, [A, B, C, D], answer, feedback)

GP = dict(key='t-gp', icon='ph:stethoscope-duotone', hue=35, label='Track 1', title='General practice',
  blurb='Assess, make it safe, titrate against targets.',
  scope=['Prescribing authority for ADHD medicines differs by state and territory. Check yours before acting.'],
  lessons=[
   ('Assess and triage', ['A positive ASRS screen earns a full assessment. It is not a diagnosis. Establish three things: enough symptoms now, several present before age 12, impairment in two or more settings.', 'Time course separates the differentials. ADHD is lifelong and trait-like. Mood disorders come in episodes.'],
    ['ASRS Part A: four or more in the shaded range means assess further.', 'Ask about sleep and substances every time. Both amplify and both are treatable.', 'Refer: psychosis, bipolar disorder, active dependence, significant cardiac disease, pregnancy, diagnostic doubt.'],
    'A patient describes two-week stretches of three hours’ sleep, feeling unstoppable and overspending, between ordinary months. Priority?', ['Start a stimulant, review in a month', 'Treat as anxiety first', 'Assess for bipolar disorder before any stimulant', 'Order a sleep study'], 'C', 'Episodic elevated mood is assessed first. Stimulants can destabilise untreated bipolar disorder.'),
   ('Baseline and safe prescribing', ['Stimulants raise heart rate and blood pressure a little on average. You only know who that matters for if you measured first.', 'Substance use is more common in untreated ADHD. Past misuse changes the choice of medicine and the monitoring, not the right to treatment.'],
    ['Before starting: blood pressure, heart rate, weight, cardiac history, family history of sudden death under 40. ECG only if flagged.', 'Misuse concern: long-acting formulation, real-time prescription monitoring, one prescriber, one pharmacy.', 'Never combine stimulants with monoamine oxidase inhibitors. Raise pregnancy plans at the first visit.'],
    'Normal blood pressure, no symptoms, but his brother died suddenly at 36. Next step?', ['Cardiology advice before starting', 'Start low and recheck in a month', 'No action; ECGs are never needed', 'Decline to treat'], 'A', 'Early sudden death in a first-degree relative is the flag that warrants cardiac assessment first.'),
   ('Titrate, review, hold continuity', ['Agree on two or three problems the patient chose, rated 0 to 10, and titrate against those. Ask when the medicine starts working and when it wears off.', 'Fix the fixable before escalating: breakfast before the dose for appetite, earlier dosing for insomnia. If one stimulant class fails, try the other.'],
    ['Every review: blood pressure, heart rate, weight, target ratings. Yearly: still needed, still the right dose?', 'Not working: check adherence, timing, sleep and comorbidity before raising the dose.', 'Give the patient a one-page written plan. Plan interstate moves early; rules differ.'],
    'On a long-acting stimulant taken at 10.30am, she cannot fall asleep before 1am. First step?', ['Add a night-time sedative', 'Stop the stimulant', 'Move the dose earlier, review sleep in two weeks', 'Reassure and wait'], 'C', 'Timing is the first lever. A late-morning dose can still be active at midnight.')],
  final=[('Which referral to an occupational therapist is most useful?', ['“ADHD. Please see.”', '“Struggling generally, for assessment.”', '“Please advise on medication.”', '“Late to work four days in five; goal is on time four in five. Please assess the morning routine.”'], 'D', 'A baseline and a target make the referral measurable for everyone.')],
  sources=['Australian Evidence-Based Clinical Practice Guideline for ADHD (AADPA, 2022)', 'Adult ADHD Self-Report Scale (ASRS-v1.1), World Health Organization'])

PSY = dict(key='t-psy', icon='ph:brain-duotone', hue=260, label='Track 2', title='Psychology',
  blurb='An assessment that holds up, and therapy built for ADHD.',
  scope=['Medication decisions belong to the prescriber. Your observations of response and side effects are useful to them.'],
  lessons=[
   ('Assessment that holds up', ['Use a structured interview such as the DIVA-5 and get a concrete example for every criterion you endorse. Rating scales are sensitive, not specific: anxiety, depression and poor sleep all score high.', 'ADHD is developmental. Inattention that began in adulthood, after trauma or illness, needs another explanation first.'],
    ['Seek collateral. Missing childhood records lower certainty; they do not exclude the diagnosis. Document what you could not obtain.', 'Overlap is the rule. Formulate what each condition explains rather than picking one.', 'Lifelong and continuous points to ADHD. Episodic points to a mood disorder.'],
    'A client scores very high on a self-report ADHD scale. What does that tell you?', ['She has ADHD', 'A thorough assessment is warranted', 'She is exaggerating', 'No interview is needed'], 'B', 'High scores also occur in anxiety, depression and sleep deprivation.'),
   ('Therapy built for ADHD, and the team', ['Cognitive behavioural therapy designed for adult ADHD improves symptoms and functioning on top of medication. The active ingredient is structured skills practice: one calendar, one task list, first steps small enough to start now. Expect the system to collapse; restarting without self-criticism is the skill.', 'Emotional dysregulation is common in adult ADHD though absent from the criteria. “Rejection sensitive dysphoria” describes a real experience but is not a diagnosis.'],
    ['Every session ends with one small, specific practice task. Adapt the frame: visible agenda, written summary, reminders.', 'Shame drives avoidance. After a late diagnosis, make room for grief before skills.', 'Suicide risk is raised in ADHD. Ask directly, write a safety plan, tell the GP.'],
    'A client keeps abandoning her planner after a bad week. Best response?', ['Suggest she is not motivated', 'Give her a more complex system', 'Treat restarting as the skill and agree a simple restart routine', 'Move to another topic'], 'C', 'Lapses are expected. A rehearsed restart matters more than a perfect streak.')],
  final=[('She says her medication makes her feel flat and asks whether to halve it.', ['Help her describe what she notices and support a prompt review with her prescriber', 'Tell her to halve it', 'Tell her to stop', 'Say it is not your area and move on'], 'A', 'Pass the observation on. The dosing decision belongs with the prescriber.'),
         ('In passing, a client says “everyone would be better off without me”.', ['Let it pass to preserve rapport', 'Wait until next session', 'Change the subject', 'Ask directly about suicidal thoughts and assess risk now'], 'D', 'A remark like this is a cue to ask directly, now.')],
  sources=['Australian Evidence-Based Clinical Practice Guideline for ADHD (AADPA, 2022)', 'Safren et al., CBT vs relaxation with educational support for medication-treated adults with ADHD, JAMA, 2010', 'Beheshti et al., Emotion dysregulation in adults with ADHD: a meta-analysis, BMC Psychiatry, 2020'])

OT = dict(key='t-ot', icon='ph:puzzle-piece-duotone', hue=150, label='Track 3', title='Occupational therapy',
  blurb='Start from what fails, then scaffold time, tasks and environment.',
  scope=['Trial evidence for occupational therapy in adult ADHD is small. Measure your own outcomes.'],
  lessons=[
   ('Assess from the occupation', ['Start with the COPM: the person names up to five daily activities going worst and rates performance and satisfaction from 1 to 10. That is your baseline and your outcome.', 'Walk through a weekday hour by hour. Breakdowns cluster at transitions. Then name the executive demand that fails: starting, sequencing, estimating time, holding steps in mind, shifting or stopping.'],
    ['COPM: a change of two or more points is clinically meaningful. Re-score at eight to twelve weeks.', 'Find a routine that already works and copy its conditions.', 'Observe the task where you can. What people report and what they do differ.'],
    'A client is always on time for football training but late for work. Most useful step?', ['Tell him to care more about work', 'Conclude it is motivation', 'Refer on', 'Identify what makes football work, such as a lift and a packed bag, and apply it to mornings'], 'D', 'Success conditions transfer. That is why you map the day.'),
   ('Scaffold, adjust, hand on', ['Make time visible with analogue clocks and visual timers where time is lost. Put the cue where the action happens, give each essential item one home, and remove steps before adding systems.', 'Use CO-OP: goal, plan, do, check. You ask the questions; the person generates the strategy, which is why it lasts.'],
    ['Sensory and workplace changes: trial one at a time and re-rate the goal. Evidence is thin; say so.', 'Reasonable adjustments are a legal duty under the Disability Discrimination Act 1992. JobAccess advises and may fund. Disclosure is the person’s choice.', 'Plan hard tasks inside the medication window. Refer mood, risk, sleep and eating concerns promptly.'],
    'He keeps forgetting medication kept in a bathroom cabinet. Simplest effective change?', ['A more detailed reminder app', 'Move it beside something he does every morning, such as the kettle', 'A talk about adherence', 'A weekly check-in call'], 'B', 'A cue tied to an existing habit at the point of performance beats a reminder that can be dismissed.')],
  final=[('A client wants adjustments at work but fears telling her manager she has ADHD.', ['She must disclose the diagnosis in full', 'She should never disclose', 'Disclosure is her choice; help her weigh it and frame requests around specific needs', 'Adjustments are not available for ADHD'], 'C', 'Requests can be framed as needs. How much to disclose is hers to decide.'),
         ('On a home visit, a client says she has been thinking about ending her life.', ['Follow your risk pathway now and inform her GP', 'Note it for next session', 'Keep it confidential', 'Change the subject'], 'A', 'Act immediately, through your risk pathway and the GP.')],
  sources=['Australian Evidence-Based Clinical Practice Guideline for ADHD (AADPA, 2022)', 'Canadian Occupational Performance Measure (COPM), 5th edition', 'JobAccess, Australian Government'])

EP = dict(key='t-ep', icon='ph:person-simple-run-duotone', hue=5, label='Track 4', title='Exercise physiology',
  blurb='Safe on stimulants, honest about the effect, designed to last.',
  scope=['Exercise is an adjunct. It does not replace assessment or first-line treatment.'],
  lessons=[
   ('Safe on stimulants', ['Run the Adult Pre-Exercise Screening System and add a full medicine and supplement list, including the time ADHD medication is taken. Record resting heart rate and blood pressure at baseline.', 'Stimulants raise heart rate, so age-predicted zones overstate effort. Prescribe by perceived exertion and the talk test. Appetite suppression means many clients arrive under-fuelled: ask when they last ate.'],
    ['Pre-workout caffeine adds to the stimulant’s effect on heart rate and blood pressure. Drop it.', 'Red flags: chest pain, fainting, sustained palpitations, unusual breathlessness. Stop and refer.', 'Report with the numbers and the time of the last dose. Do not advise on medication.'],
    'A new client takes lisdexamfetamine and uses a caffeine pre-workout. First priority?', ['Ignore it; supplements are his business', 'Advise dropping the pre-workout', 'Double the warm-up', 'Refuse to train him'], 'B', 'Stimulant plus high-dose caffeine is additive. Removing it is the simplest safety step.'),
   ('Dose it, and design it to last', ['Twenty to thirty minutes of moderate aerobic exercise gives a small to moderate lift in attention and executive function for about an hour. Place it directly before demanding mental work. Aerobic exercise has the best support; mind-body exercise shows a small effect, and coordinative exercise has too few studies to call.', 'Dropout is an executive problem, not a motivation problem.'],
    ['Design for adherence: short, varied, fixed time, a partner expecting them, immediate feedback, near-zero set-up.', 'Agree a minimum session and “never miss twice”. After a lapse: no comment, lower load, rebook on the spot.', 'Send the prescriber resting heart rate and blood pressure trends and any unintended weight loss.'],
    'A student struggles most with afternoon study. When is exercise most useful?', ['Late at night', 'Only at weekends', 'First thing, six hours earlier', 'A brisk 20 to 30 minutes just before the study block'], 'D', 'The effect lasts about an hour, so place it directly before the task.')],
  final=[('Mid-session, a client on a stimulant reports sudden palpitations and light-headedness.', ['Stop, monitor, and arrange medical review before further exercise', 'Lower the intensity and continue', 'Give water and continue', 'Suggest skipping tomorrow’s medication'], 'A', 'New cardiac symptoms on a stimulant need medical review first.'),
         ('He asks whether exercise can replace his medication.', ['Yes, if he trains hard enough', 'Only weights help', 'It gives a modest, short-lived lift and is an addition; medication decisions are for his prescriber', 'There is no benefit at all'], 'C', 'Be accurate about the size of the effect and keep medication with the prescriber.')],
  sources=['Exercise and Sports Science Australia: Adult Pre-Exercise Screening System', 'Australian Evidence-Based Clinical Practice Guideline for ADHD (AADPA, 2022)', 'Module 06 of this course: acute exercise and cognition'])

NUT = dict(key='t-nut', icon='ph:leaf-duotone', hue=110, label='Track 5', title='Nutrition',
  blurb='Appetite on stimulants, red flags, and the diet evidence stated plainly.',
  scope=['Medical nutrition therapy and eating disorders belong with an Accredited Practising Dietitian.'],
  lessons=[
   ('Appetite, weight and red flags', ['Reduced appetite is the commonest stimulant side effect. Hunger vanishes through the middle of the day and returns hard in the evening. Plan around it: a substantial breakfast with protein before the dose, then eating by the clock, with alarms and small energy-dense food.', 'Keep food low-effort: five default meals and a saved grocery order outlast any detailed meal plan.'],
    ['Weigh regularly. Unintended loss of about five per cent in three months: tell the GP.', 'ADHD carries higher rates of binge eating and bulimia. SCOFF: two or more positive answers means refer.', 'Medication decisions are the prescriber’s. Help the client raise appetite at their next review.'],
    'She asks whether to stop her ADHD medication because it ruins her appetite.', ['Yes, appetite matters more', 'No, never stop it', 'Try halving it', 'That is for her prescriber; you will help with eating strategies and suggest she raises it at review'], 'D', 'Your part is the eating strategy and encouraging the conversation.'),
   ('The evidence, stated plainly', ['Omega-3 shows a small effect at best, mostly in children, far below medication. Elimination diets have little adult evidence and real risks of inadequacy and disordered eating; they are not routine. Sugar has not been shown to cause or worsen ADHD, and links between eating pattern and ADHD are observational only. The priority is regular, varied, adequate meals.', 'Micronutrients: test where deficiency is plausible, then correct. Never supplement iron blind.'],
    ['Caffeine adds to stimulant effects on heart rate, anxiety and sleep. Ask how much and when.', 'Tell the GP every supplement the client takes. Patients often do not.', 'Useful wording: “The effect is small, and it would be in addition to your treatment, not instead of it.”'],
    'She wants fish oil instead of starting medication.', ['The evidence shows a small benefit only; it will not replace medication, and that decision is one for her and her doctor', 'Fish oil works as well as medication', 'Fish oil is dangerous', 'She must take medication'], 'A', 'State the size of the effect and keep the medication decision with her doctor.')],
  final=[('A client answers yes to three SCOFF questions.', ['Start a meal plan yourself', 'Reassure her', 'Refer to her GP and an eating disorder-experienced dietitian', 'Recommend a weight-loss programme'], 'C', 'A positive screen needs medical and specialist dietetic assessment.'),
         ('On a stimulant, she drinks four energy drinks a day and sleeps poorly.', ['Add magnesium', 'Reduce caffeine, especially after midday, and mention it to her prescriber', 'Add iron', 'Nothing; caffeine is unrelated'], 'B', 'High caffeine with a stimulant is a likely, fixable cause of poor sleep.')],
  sources=['Australian Evidence-Based Clinical Practice Guideline for ADHD (AADPA, 2022)', 'Dietitians Australia: find an Accredited Practising Dietitian', 'Morgan, Reid and Lacey, The SCOFF questionnaire, BMJ, 1999'])

NAT = dict(key='t-nat', icon='ph:plant-duotone', hue=80, label='Track 6', title='Naturopathy',
  blurb='Safe scope beside medical care, interactions, and the evidence stated plainly.',
  scope=['You work as an adjunct to medical care. Never advise stopping, reducing or delaying prescribed medication.'],
  lessons=[
   ('Scope and red flags', ['Diagnosis and medication decisions belong to medical practitioners. A client who suspects ADHD needs assessment by a GP first, not supplements. A client who wants to change medication takes that to their prescriber, with your support.', 'Take a complete list at the first visit: prescriptions with dose and timing, over-the-counter products, herbs, energy drinks, pre-workout powders and recreational substances.'],
    ['Refer urgently: suicidal thoughts, chest pain, fainting or palpitations on a stimulant, signs of mania or psychosis.', 'Refer promptly: rapid weight loss, suspected eating disorder, pregnancy or planned pregnancy.', 'You cannot check interactions with a medicine you did not ask about.'],
    'A client wants to stop her ADHD medication and “go natural”.', ['Design a herbal protocol', 'Tell her to taper over two weeks', 'Suggest she halves it first', 'Encourage her to discuss it with her prescriber first, and offer support alongside whatever they decide'], 'D', 'Changes to prescribed medication are made with the prescriber.'),
   ('Interactions that matter', ['Guarana, high-dose caffeine, bitter orange (synephrine) and yohimbe all add to a stimulant’s effect on heart rate and blood pressure. Ephedra is not legally available in Australia. Check “energy”, “fat-burner” and “pre-workout” blends, which often combine several.', 'St John’s wort speeds the breakdown of many medicines, including the contraceptive pill, and risks serotonin toxicity with antidepressants, which many adults with ADHD take.'],
    ['Liquorice in regular amounts can raise blood pressure.', 'Kava carries liver warnings. Sedating herbs add to alcohol and other sedatives.', 'Melatonin is a scheduled medicine in Australia. Lead with sleep routine, and ask a pharmacist when unsure.'],
    'On a stimulant, an SSRI and the contraceptive pill, she asks about St John’s wort for mood.', ['It is a safe addition', 'Advise against it: serotonin toxicity risk with the SSRI, and it can make the pill less effective', 'It is fine as a tea', 'It interacts only with the stimulant'], 'B', 'Two clinically important interactions, either one reason enough.'),
   ('The evidence, and the team', ['Omega-3 shows a small effect at best. Correcting a deficiency confirmed by testing is sound care. Saffron, pine bark extract, bacopa and ginkgo rest on a few small, short trials, mostly in children: promising is not proven. Homeopathy has no reliable evidence for any condition (NHMRC, 2015), and detoxes and megavitamins have none in ADHD. These cost money and delay effective care.', 'Regular sleep, regular meals and daily movement have better support than any product.'],
    ['One or two changes at a time. Long protocols fail and add shame.', 'With consent, write to the GP: product, dose, start date.', 'Every recommendation gets a target and a review at eight to twelve weeks. No benefit: stop it.'],
    'A parent asks about a homeopathic remedy for her adult son’s ADHD.', ['Supply it, since it cannot hurt', 'Recommend it with a detox', 'Explain there is no reliable evidence it works, and steer towards assessment and what does help', 'Avoid answering'], 'C', 'Honesty about ineffective treatments protects the client’s money and time.')],
  final=[('A new client believes she has ADHD and asks for herbs to treat it.', ['Recommend she sees her GP for assessment, and offer general wellbeing support meanwhile', 'Begin a herbal protocol', 'Order functional testing', 'Tell her ADHD is overdiagnosed'], 'A', 'Assessment comes first. Treating an undiagnosed condition delays proper care.')],
  sources=['Australian Evidence-Based Clinical Practice Guideline for ADHD (AADPA, 2022)', 'NHMRC, Evidence on the effectiveness of homeopathy for treating health conditions, 2015', 'Therapeutic Goods Administration: safety information on kava and St John’s wort'])

TRACKS = [GP, PSY, OT, EP, NUT, NAT]
