# Sketchy-method visual layer for the discipline tracks.
# SHARED = the recurring cross-track vocabulary, defined ONCE and <use>d everywhere.
# SCENES[track_key] = one persistent world + at most 8 symbols (the coherence cap).
# All art is PLACEHOLDER geometry. Replace the inner markup of any <symbol>; ids, positions and logic stay as they are.
# In art: stroke/fill "currentColor" = ink, var(--sk-accent) = the scene's single accent colour.

INK = 'currentColor'

SHARED = {
 # --- guideline recommendation strength: solid stamp vs dashed stamp
 'sk-stamp-strong': ('Guideline: strong recommendation', '<circle cx="50" cy="50" r="40" fill="#1c1917"/><circle cx="50" cy="50" r="31" fill="none" stroke="#fdfbf7" stroke-width="3"/><path d="M33 51 l11 11 l24 -26" fill="none" stroke="#fdfbf7" stroke-width="8" stroke-linecap="round" stroke-linejoin="round"/>'),
 'sk-stamp-weak': ('Guideline: conditional recommendation', '<circle cx="50" cy="50" r="40" fill="#fdfbf7" stroke="#1c1917" stroke-width="5" stroke-dasharray="9 7"/><path d="M33 51 l11 11 l24 -26" fill="none" stroke="#1c1917" stroke-width="7" stroke-linecap="round" stroke-linejoin="round" stroke-dasharray="7 6"/>'),
 # --- certainty of evidence (GRADE): gold / silver / bronze / grey shield
 'sk-shield-high': ('Evidence certainty: high', '<path d="M50 8 L86 22 V52 C86 72 70 86 50 94 C30 86 14 72 14 52 V22 Z" fill="#e0a915" stroke="#1c1917" stroke-width="5" stroke-linejoin="round"/><text x="50" y="62" text-anchor="middle" font-family="Helvetica,Arial,sans-serif" font-weight="800" font-size="34" fill="#1c1917">H</text>'),
 'sk-shield-mod': ('Evidence certainty: moderate', '<path d="M50 8 L86 22 V52 C86 72 70 86 50 94 C30 86 14 72 14 52 V22 Z" fill="#c9ced6" stroke="#1c1917" stroke-width="5" stroke-linejoin="round"/><text x="50" y="62" text-anchor="middle" font-family="Helvetica,Arial,sans-serif" font-weight="800" font-size="34" fill="#1c1917">M</text>'),
 'sk-shield-low': ('Evidence certainty: low', '<path d="M50 8 L86 22 V52 C86 72 70 86 50 94 C30 86 14 72 14 52 V22 Z" fill="#c98a54" stroke="#1c1917" stroke-width="5" stroke-linejoin="round"/><text x="50" y="62" text-anchor="middle" font-family="Helvetica,Arial,sans-serif" font-weight="800" font-size="34" fill="#1c1917">L</text>'),
 'sk-shield-vlow': ('Evidence certainty: very low', '<path d="M50 8 L86 22 V52 C86 72 70 86 50 94 C30 86 14 72 14 52 V22 Z" fill="#8d8d8d" stroke="#1c1917" stroke-width="5" stroke-linejoin="round" stroke-dasharray="8 6"/><text x="50" y="62" text-anchor="middle" font-family="Helvetica,Arial,sans-serif" font-weight="800" font-size="30" fill="#fdfbf7">VL</text>'),
 # --- the myth-buster: identical in every scene
 'sk-myth': ('Myth-buster', '<ellipse cx="50" cy="93" rx="26" ry="4" fill="#000" opacity=".15"/><path d="M50 22 C66 22 74 32 72 50 C70 62 78 74 72 86 C66 94 34 94 28 86 C22 74 30 62 28 50 C26 32 34 22 50 22 Z" fill="#d96b52" stroke="#1c1917" stroke-width="4" stroke-linejoin="round"/><circle cx="43" cy="48" r="3" fill="#1c1917"/><circle cx="57" cy="48" r="3" fill="#1c1917"/><path d="M44 60 Q50 55 56 60" fill="none" stroke="#1c1917" stroke-width="3" stroke-linecap="round"/><path d="M36 40 l10 3 M64 40 l-10 3" stroke="#1c1917" stroke-width="3" stroke-linecap="round"/><circle cx="76" cy="24" r="17" fill="#fdfbf7" stroke="#b91a24" stroke-width="5"/><path d="M65 13 L87 35" stroke="#b91a24" stroke-width="5" stroke-linecap="round"/>'),
 # --- referral / handoff: the signpost
 'sk-signpost': ('Referral pathway', '<rect x="46" y="14" width="8" height="78" rx="3" fill="#1c1917"/><path d="M54 22 H84 L94 33 L84 44 H54 Z" fill="#8fbfe3" stroke="#1c1917" stroke-width="4" stroke-linejoin="round"/><path d="M46 50 H16 L6 61 L16 72 H46 Z" fill="#fdfbf7" stroke="#1c1917" stroke-width="4" stroke-linejoin="round"/><path d="M62 33 h16 m-6 -6 l6 6 l-6 6" fill="none" stroke="#1c1917" stroke-width="3.5" stroke-linecap="round" stroke-linejoin="round"/>'),
}

def S(id, title, encodes, recap, cues, x, y, size, art, badge=None, shared=None, lesson=''):
    return dict(id=id, title=title, encodes=encodes, recap=recap, cues=cues, x=x, y=y, size=size, art=art, badge=badge, shared=shared, lesson=lesson)

F = 'font-family="Helvetica,Arial,sans-serif" font-weight="800"'

SCENES = {
 # ================================================================ OCCUPATIONAL THERAPY
 't-ot': dict(world='The adaptation workshop', minutes=5, palette=('#f6ecce', '#d9c9a3', '#1c1917', '#2f8f6b'),
  desc='A room being modified for someone with ADHD: a workbench at the left, a wall with a schedule and a clock, a door with a hook at the right.',
  backdrop='''<rect width="800" height="450" fill="var(--sk-b1)"/><rect y="330" width="800" height="120" fill="var(--sk-b2)"/><line x1="0" y1="330" x2="800" y2="330" stroke="currentColor" stroke-width="3"/>
<rect x="40" y="250" width="250" height="16" rx="4" fill="var(--sk-b2)" stroke="currentColor" stroke-width="3"/><rect x="56" y="266" width="12" height="80" fill="currentColor"/><rect x="262" y="266" width="12" height="80" fill="currentColor"/>
<rect x="640" y="120" width="120" height="226" rx="6" fill="#fdfbf7" stroke="currentColor" stroke-width="3"/><circle cx="660" cy="240" r="6" fill="currentColor"/>
<rect x="470" y="60" width="130" height="90" rx="6" fill="#fdfbf7" stroke="currentColor" stroke-width="3"/><line x1="535" y1="60" x2="535" y2="150" stroke="currentColor" stroke-width="3"/>''',
  symbols=[
   S('ot1', 'The COP with the tape Measure', 'A police cap resting on a tape measure marked plus two: the COPM, where a change of two or more points is clinically meaningful.', 'COPM: person-chosen goals rated 1 to 10. A change of 2 or more points matters.', ['sound-alike pun (COP + Measure)', 'position: on the workbench, where work starts'], 70, 150, 110,
     f'<rect x="8" y="60" width="84" height="18" rx="4" fill="#fdfbf7" stroke="{INK}" stroke-width="4"/><path d="M20 60 v8 M32 60 v12 M44 60 v8 M56 60 v12 M68 60 v8 M80 60 v12" stroke="{INK}" stroke-width="3"/><path d="M26 44 q24 -26 48 0 v8 h-48 z" fill="{INK}"/><rect x="20" y="50" width="60" height="8" rx="4" fill="var(--sk-accent)"/><circle cx="50" cy="36" r="5" fill="var(--sk-accent)"/><text x="78" y="98" text-anchor="middle" {F} font-size="20" fill="var(--sk-accent)">+2</text>', lesson='Module 1, lesson 1'),
   S('ot2', 'The schedule with glowing doorways', 'A wall schedule where the gaps between blocks glow: breakdowns cluster at transitions between activities.', 'Map the day. Breakdowns cluster at transitions, so look there first.', ['colour: accent marks the gaps, not the blocks', 'position: on the wall, the overview of the day'], 320, 70, 120,
     f'<rect x="8" y="10" width="84" height="80" rx="6" fill="#fdfbf7" stroke="{INK}" stroke-width="4"/><rect x="18" y="20" width="64" height="12" rx="3" fill="{INK}" opacity=".75"/><rect x="18" y="44" width="64" height="12" rx="3" fill="{INK}" opacity=".75"/><rect x="18" y="68" width="64" height="12" rx="3" fill="{INK}" opacity=".75"/><rect x="18" y="33" width="64" height="10" rx="3" fill="var(--sk-accent)"/><rect x="18" y="57" width="64" height="10" rx="3" fill="var(--sk-accent)"/>', lesson='Module 1, lesson 2'),
   S('ot3', 'The clock you can see', 'An analogue clock with a shaded wedge of remaining time: make time visible where it is lost.', 'Make time visible: analogue clocks and visual timers where time disappears.', ['action: the wedge visibly shrinks', 'position: high on the wall, always in sight'], 480, 170, 100,
     f'<circle cx="50" cy="50" r="40" fill="#fdfbf7" stroke="{INK}" stroke-width="5"/><path d="M50 50 L50 14 A36 36 0 0 1 84 62 Z" fill="var(--sk-accent)" opacity=".85"/><path d="M50 50 V22 M50 50 L70 60" stroke="{INK}" stroke-width="5" stroke-linecap="round"/><circle cx="50" cy="50" r="4" fill="{INK}"/>', lesson='Module 2, lesson 1'),
   S('ot4', 'The hook by the door', 'Keys hanging on a hook right beside the door: the cue lives at the point of performance, and each item has one home.', 'Put the cue where the action happens. One home for each essential item.', ['position: beside the door, the point of performance', 'proximity: next to the referral signpost, both are about leaving'], 560, 210, 90,
     f'<path d="M30 14 h40 v10 h-14 v14 a12 12 0 1 1 -12 0 v-14 h-14 z" fill="{INK}"/><circle cx="50" cy="62" r="14" fill="none" stroke="var(--sk-accent)" stroke-width="7"/><path d="M50 76 v16 m0 -6 h8 m-8 -6 h6" stroke="var(--sk-accent)" stroke-width="6" stroke-linecap="round"/>', lesson='Module 2, lesson 2'),
   S('ot5', 'The chicken CO-OP', 'A chicken coop holding four eggs lettered G, P, D and C: the CO-OP approach, Goal, Plan, Do, Check, where the person hatches their own strategy.', 'CO-OP: Goal, Plan, Do, Check. Guide with questions; the person owns the strategy.', ['sound-alike pun (coop = CO-OP)', 'action: the person hatches the plan, not the therapist'], 190, 145, 110,
     f'<path d="M10 46 L50 14 L90 46 V86 H10 Z" fill="var(--sk-b2)" stroke="{INK}" stroke-width="4" stroke-linejoin="round"/><g {F} font-size="13" text-anchor="middle"><ellipse cx="26" cy="68" rx="10" ry="13" fill="#fdfbf7" stroke="{INK}" stroke-width="3"/><text x="26" y="73" fill="var(--sk-accent)">G</text><ellipse cx="42" cy="68" rx="10" ry="13" fill="#fdfbf7" stroke="{INK}" stroke-width="3"/><text x="42" y="73" fill="var(--sk-accent)">P</text><ellipse cx="58" cy="68" rx="10" ry="13" fill="#fdfbf7" stroke="{INK}" stroke-width="3"/><text x="58" y="73" fill="var(--sk-accent)">D</text><ellipse cx="74" cy="68" rx="10" ry="13" fill="#fdfbf7" stroke="{INK}" stroke-width="3"/><text x="74" y="73" fill="var(--sk-accent)">C</text></g>', badge='sk-shield-low', lesson='Module 2, lesson 3'),
   S('ot6', 'One pair of headphones', 'A single pair of headphones on the bench beside a tally mark: trial one sensory adjustment at a time and measure it.', 'Sensory load: trial one adjustment at a time and re-rate the goal. Evidence is thin.', ['action: one item, one tally, a single trial', 'badge: grey shield for very thin evidence'], 60, 345, 95,
     f'<path d="M18 62 V50 a32 32 0 0 1 64 0 V62" fill="none" stroke="{INK}" stroke-width="6" stroke-linecap="round"/><rect x="10" y="56" width="18" height="30" rx="8" fill="var(--sk-accent)" stroke="{INK}" stroke-width="4"/><rect x="72" y="56" width="18" height="30" rx="8" fill="var(--sk-accent)" stroke="{INK}" stroke-width="4"/><path d="M46 70 v18" stroke="{INK}" stroke-width="5" stroke-linecap="round"/>', badge='sk-shield-vlow', lesson='Module 3, lesson 1'),
   S('ot7', 'The signpost at the door', 'The referral signpost standing at the doorway: mood, risk, sleep and eating concerns leave this room for the GP, a psychologist or a dietitian.', 'Refer on for mood, risk, sleep or eating. Say what you saw and what you are asking.', ['recurring symbol: referral signpost', 'position: at the exit'], 665, 330, 100, None, shared='sk-signpost', lesson='Module 4, lesson 3'),
   S('ot8', 'The myth-buster on the workbench', 'The myth-buster crossing out the word lazy: a missed routine is an executive-function problem, not a motivation problem.', 'Myth: “they just need to try harder.” It is executive function, not motivation.', ['recurring symbol: myth-buster', 'position: on the workbench, where the blame usually lands'], 330, 320, 110, None, shared='sk-myth', lesson='Pitfall')]),

 # ================================================================ EXERCISE PHYSIOLOGY
 't-ep': dict(world='The evidence gym', minutes=5, palette=('#e8eef3', '#b9c7d3', '#1c1917', '#d96b52'),
  desc='A gym floor with an entrance desk at the left, then three stations left to right: a running track, a yoga mat and a boxing bag, each with a gauge above it.',
  backdrop='''<rect width="800" height="450" fill="var(--sk-b1)"/><rect y="340" width="800" height="110" fill="var(--sk-b2)"/><line x1="0" y1="340" x2="800" y2="340" stroke="currentColor" stroke-width="3"/>
<rect x="20" y="270" width="110" height="76" rx="6" fill="#fdfbf7" stroke="currentColor" stroke-width="3"/>
<path d="M170 410 H420" stroke="#fdfbf7" stroke-width="26" stroke-linecap="round"/><path d="M170 410 H420" stroke="currentColor" stroke-width="2" stroke-dasharray="14 12"/>
<rect x="470" y="396" width="130" height="18" rx="9" fill="#fdfbf7" stroke="currentColor" stroke-width="3"/>
<line x1="700" y1="120" x2="700" y2="190" stroke="currentColor" stroke-width="4"/>''',
  symbols=[
   S('ep1', 'The clipboard and the crossed-out can', 'A clipboard at the entrance with a pill ticked and an energy can crossed out: screen every client, list their medicines, and drop the pre-workout.', 'Screen first: full medicine list, and no pre-workout caffeine on top of a stimulant.', ['position: at the entrance, before any station', 'colour: accent cross on the can'], 30, 170, 100,
     f'<rect x="16" y="12" width="52" height="76" rx="6" fill="#fdfbf7" stroke="{INK}" stroke-width="4"/><rect x="32" y="6" width="20" height="12" rx="4" fill="{INK}"/><rect x="24" y="30" width="18" height="9" rx="4.5" fill="{INK}"/><path d="M48 35 l4 4 l8 -9" fill="none" stroke="{INK}" stroke-width="3.5" stroke-linecap="round"/><rect x="66" y="44" width="24" height="42" rx="5" fill="#fdfbf7" stroke="{INK}" stroke-width="4"/><path d="M62 40 L94 90 M94 40 L62 90" stroke="var(--sk-accent)" stroke-width="6" stroke-linecap="round"/>', lesson='Module 1, lesson 1'),
   S('ep2', 'The running track and its half-full gauge', 'A runner beneath a gauge pointing to the middle, beside an hourglass: twenty to thirty minutes of aerobic work gives a small to moderate lift that lasts about an hour.', 'Aerobic, 20 to 30 min: small to moderate lift in attention for about an hour.', ['action: the gauge needle shows effect size', 'proximity: hourglass beside it shows the effect is short'], 235, 250, 120,
     f'<path d="M14 40 A30 30 0 0 1 74 40" fill="none" stroke="{INK}" stroke-width="6" stroke-linecap="round"/><path d="M14 40 A30 30 0 0 1 44 10" fill="none" stroke="var(--sk-accent)" stroke-width="6" stroke-linecap="round"/><path d="M44 40 L44 16" stroke="{INK}" stroke-width="5" stroke-linecap="round"/><circle cx="44" cy="40" r="5" fill="{INK}"/><circle cx="40" cy="58" r="6" fill="{INK}"/><path d="M40 64 l-4 16 l-10 12 M36 80 l12 8 M40 68 l12 4 M40 68 l-12 6" fill="none" stroke="{INK}" stroke-width="5" stroke-linecap="round" stroke-linejoin="round"/><path d="M76 56 h16 l-8 14 l8 14 h-16 l8 -14 z" fill="#fdfbf7" stroke="{INK}" stroke-width="3.5" stroke-linejoin="round"/>', badge='sk-shield-low', lesson='Module 2, lesson 1'),
   S('ep3', 'The yoga mat and its low gauge', 'A seated figure on a mat under a gauge pointing low: mind-body exercise helps a little, no more than other active programmes.', 'Mind-body exercise: a small effect, no better than other active programmes.', ['action: gauge needle points low', 'position: middle station, middling support'], 480, 280, 110,
     f'<path d="M18 40 A30 30 0 0 1 78 40" fill="none" stroke="{INK}" stroke-width="6" stroke-linecap="round"/><path d="M18 40 A30 30 0 0 1 26 20" fill="none" stroke="var(--sk-accent)" stroke-width="6" stroke-linecap="round"/><path d="M48 40 L28 24" stroke="{INK}" stroke-width="5" stroke-linecap="round"/><circle cx="48" cy="40" r="5" fill="{INK}"/><circle cx="48" cy="60" r="6" fill="{INK}"/><path d="M48 66 v14 M48 80 l-18 8 M48 80 l18 8 M48 70 l-14 8 M48 70 l14 8" fill="none" stroke="{INK}" stroke-width="5" stroke-linecap="round"/>', badge='sk-shield-low', lesson='Module 2, lesson 2'),
   S('ep4', 'The boxing bag and the greyed-out gauge', 'A hanging bag under a gauge with a question mark instead of a needle: coordinative exercise has too few studies to call.', 'Coordinative exercise: too few studies. Do not promise an effect.', ['colour: gauge has no accent, because there is no reading', 'position: far station, furthest from evidence'], 650, 170, 110,
     f'<path d="M18 40 A30 30 0 0 1 78 40" fill="none" stroke="{INK}" stroke-width="6" stroke-linecap="round" stroke-dasharray="7 7"/><text x="48" y="42" text-anchor="middle" {F} font-size="26" fill="{INK}">?</text><rect x="34" y="52" width="28" height="42" rx="12" fill="var(--sk-b2)" stroke="{INK}" stroke-width="4"/>', badge='sk-shield-vlow', lesson='Module 2, lesson 2'),
   S('ep5', 'The speech bubble beats the heart-rate number', 'A speech bubble sitting on top of a crossed-out heart-rate reading: on a stimulant, prescribe intensity by talk test and perceived exertion, not heart rate alone.', 'On stimulants, heart rate misleads. Use the talk test and perceived exertion.', ['action: the bubble literally overrides the number', 'colour: accent strike through the reading'], 150, 120, 105,
     f'<rect x="10" y="52" width="66" height="36" rx="6" fill="#fdfbf7" stroke="{INK}" stroke-width="4"/><text x="43" y="78" text-anchor="middle" {F} font-size="20" fill="{INK}">172</text><path d="M6 94 L80 48" stroke="var(--sk-accent)" stroke-width="6" stroke-linecap="round"/><path d="M34 8 h52 a8 8 0 0 1 8 8 v18 a8 8 0 0 1 -8 8 h-30 l-10 10 v-10 h-12 a8 8 0 0 1 -8 -8 v-18 a8 8 0 0 1 8 -8 z" fill="var(--sk-accent)" stroke="{INK}" stroke-width="4" stroke-linejoin="round"/><path d="M44 25 h32" stroke="#fdfbf7" stroke-width="5" stroke-linecap="round"/>', lesson='Module 1, lesson 2'),
   S('ep6', 'Two sneakers and a calendar with one missed day', 'A pair of sneakers beside a calendar showing one cross and never two in a row: train with a partner at a fixed time, and never miss twice.', 'Adherence: a partner, a fixed time, and the rule “never miss twice”.', ['proximity: two shoes means two people', 'action: a single cross, never a second'], 370, 120, 105,
     f'<rect x="40" y="10" width="54" height="50" rx="6" fill="#fdfbf7" stroke="{INK}" stroke-width="4"/><rect x="40" y="10" width="54" height="14" rx="6" fill="{INK}"/><path d="M50 34 l8 8 m0 -8 l-8 8" stroke="var(--sk-accent)" stroke-width="4" stroke-linecap="round"/><path d="M68 42 l4 4 l8 -10" fill="none" stroke="{INK}" stroke-width="4" stroke-linecap="round"/><path d="M6 78 q4 -14 18 -10 l14 8 q8 2 8 8 v4 h-40 z" fill="var(--sk-accent)" stroke="{INK}" stroke-width="3.5" stroke-linejoin="round"/><path d="M50 84 q4 -14 18 -10 l14 8 q8 2 8 8 v4 h-40 z" fill="var(--sk-accent)" stroke="{INK}" stroke-width="3.5" stroke-linejoin="round"/>', lesson='Module 3, lessons 2 and 3'),
   S('ep7', 'The signpost by the exit', 'The referral signpost with a heart on it: chest pain, fainting or sustained palpitations mean stop the session and refer for medical review.', 'Red flags: chest pain, fainting, palpitations. Stop and refer, with the numbers.', ['recurring symbol: referral signpost', 'position: by the exit, the way out of the session'], 560, 100, 100, None, shared='sk-signpost', lesson='Module 1, lesson 3'),
   S('ep8', 'The myth-buster at the front desk', 'The myth-buster crossing out a pill swapped for a dumbbell: exercise is a modest, short-acting addition, not a replacement for medication.', 'Myth: “exercise can replace medication.” It is a modest addition, not a substitute.', ['recurring symbol: myth-buster', 'position: at the front desk, where the question gets asked'], 20, 345, 100, None, shared='sk-myth', lesson='Pitfall')]),

 # ================================================================ PSYCHOLOGY
 't-psy': dict(world='The clinic reception and triage desk', minutes=5, palette=('#ecebf5', '#c9c6e0', '#1c1917', '#5b54c7'),
  desc='A clinic reception: a desk at the left, filing drawers behind it, a floor timeline running across the room, and a branching signpost at the right leading to treatment.',
  backdrop='''<rect width="800" height="450" fill="var(--sk-b1)"/><rect y="335" width="800" height="115" fill="var(--sk-b2)"/><line x1="0" y1="335" x2="800" y2="335" stroke="currentColor" stroke-width="3"/>
<rect x="30" y="240" width="240" height="100" rx="8" fill="#fdfbf7" stroke="currentColor" stroke-width="3"/><rect x="30" y="240" width="240" height="16" rx="6" fill="currentColor"/>
<rect x="300" y="70" width="130" height="180" rx="6" fill="#fdfbf7" stroke="currentColor" stroke-width="3"/><line x1="300" y1="130" x2="430" y2="130" stroke="currentColor" stroke-width="3"/><line x1="300" y1="190" x2="430" y2="190" stroke="currentColor" stroke-width="3"/>''',
  symbols=[
   S('psy1', 'The DIVA at the desk', 'A stage microphone on the reception desk with a speech bubble of examples: the DIVA-5 structured interview, where every criterion needs a real example.', 'Structured interview (DIVA-5): an example for every criterion you endorse.', ['sound-alike pun (diva = DIVA-5)', 'position: on the desk, the first thing a client meets'], 60, 140, 105,
     f'<rect x="40" y="10" width="22" height="40" rx="11" fill="var(--sk-accent)" stroke="{INK}" stroke-width="4"/><path d="M32 40 a19 19 0 0 0 38 0 M51 60 v20 M36 84 h30" fill="none" stroke="{INK}" stroke-width="5" stroke-linecap="round"/><path d="M70 14 l10 -8 M74 28 h14 M70 42 l10 8" stroke="var(--sk-accent)" stroke-width="4" stroke-linecap="round"/>', lesson='Module 1, lesson 1'),
   S('psy2', 'One full drawer, one empty drawer', 'A filing cabinet with a school report poking out of one drawer and another drawer empty but still labelled: seek collateral, and know that missing records do not rule ADHD out.', 'Seek collateral. Missing records lower certainty; they do not exclude ADHD.', ['proximity: the full and the empty drawer sit together', 'colour: accent on the report that exists'], 315, 85, 100,
     f'<rect x="12" y="10" width="76" height="34" rx="4" fill="#fdfbf7" stroke="{INK}" stroke-width="4"/><rect x="26" y="0" width="34" height="22" rx="3" fill="var(--sk-accent)" stroke="{INK}" stroke-width="3"/><rect x="12" y="52" width="76" height="34" rx="4" fill="#fdfbf7" stroke="{INK}" stroke-width="4" stroke-dasharray="7 6"/><rect x="40" y="26" width="20" height="7" rx="3" fill="{INK}"/><rect x="40" y="68" width="20" height="7" rx="3" fill="{INK}"/>', lesson='Module 1, lesson 2'),
   S('psy3', 'The floor line that never breaks, and the one that comes in waves', 'Two lines on the floor: one solid and continuous, one in separate humps. ADHD is lifelong and trait-like; mood disorders come in episodes.', 'Time course: ADHD is continuous and lifelong. Mood disorders come in episodes.', ['action: one line runs unbroken, the other rises and falls', 'position: along the floor, the path through a life'], 60, 350, 130,
     f'<path d="M6 30 H94" stroke="var(--sk-accent)" stroke-width="7" stroke-linecap="round"/><path d="M6 78 q10 -26 20 0 M40 78 q10 -26 20 0 M74 78 q10 -26 20 0" fill="none" stroke="{INK}" stroke-width="6" stroke-linecap="round"/><text x="50" y="18" text-anchor="middle" {F} font-size="13" fill="var(--sk-accent)">ADHD</text><text x="50" y="98" text-anchor="middle" {F} font-size="13" fill="{INK}">episodes</text>', lesson='Module 1, lesson 3'),
   S('psy4', 'The branching therapy signpost', 'A signpost with three arms for adults, teens and children, each carrying a recommendation stamp: ADHD-specific cognitive behavioural therapy adds benefit for adults on top of medication, and the recommendation differs by age group.', 'ADHD-specific CBT adds benefit for adults, on top of medication. Check the age-specific recommendation.', ['position: the fork between assessment and treatment', 'badge: recommendation stamp on each arm'], 520, 110, 150,
     f'<rect x="46" y="10" width="8" height="84" rx="3" fill="{INK}"/><g {F} font-size="11"><path d="M54 14 H88 L96 23 L88 32 H54 Z" fill="var(--sk-accent)" stroke="{INK}" stroke-width="3" stroke-linejoin="round"/><text x="72" y="27" text-anchor="middle" fill="#fdfbf7">ADULTS</text><path d="M46 38 H14 L6 47 L14 56 H46 Z" fill="#fdfbf7" stroke="{INK}" stroke-width="3" stroke-linejoin="round"/><text x="28" y="51" text-anchor="middle" fill="{INK}">TEENS</text><path d="M54 62 H88 L96 71 L88 80 H54 Z" fill="#fdfbf7" stroke="{INK}" stroke-width="3" stroke-linejoin="round"/><text x="73" y="75" text-anchor="middle" fill="{INK}">CHILD</text></g>', badge='sk-stamp-weak', lesson='Module 2, lesson 1'),
   S('psy5', 'One calendar, one list', 'A single calendar clipped to a single list: the core skill is one calendar and one task list, checked at the same time each day.', 'Core skill: one calendar, one task list, checked at the same time daily.', ['proximity: the two are clipped together as one system', 'colour: accent on the single shared clip'], 700, 250, 90,
     f'<rect x="8" y="16" width="46" height="60" rx="5" fill="#fdfbf7" stroke="{INK}" stroke-width="4"/><rect x="8" y="16" width="46" height="14" rx="5" fill="{INK}"/><rect x="46" y="28" width="46" height="60" rx="5" fill="#fdfbf7" stroke="{INK}" stroke-width="4"/><path d="M56 44 h26 M56 56 h26 M56 68 h18" stroke="{INK}" stroke-width="4" stroke-linecap="round"/><rect x="42" y="8" width="18" height="16" rx="4" fill="var(--sk-accent)" stroke="{INK}" stroke-width="3"/>', lesson='Module 2, lesson 2'),
   S('psy6', 'The storm cloud with an umbrella', 'A small storm cloud raining on a heart that holds an umbrella: emotional dysregulation is common in adult ADHD though absent from the criteria, and it can be worked on.', 'Emotional dysregulation is common in adult ADHD, and it is workable.', ['action: the storm passes quickly; the umbrella is the skill', 'colour: accent umbrella'], 440, 270, 100,
     f'<path d="M22 40 a14 14 0 0 1 8 -26 a18 18 0 0 1 34 4 a13 13 0 0 1 4 24 z" fill="#fdfbf7" stroke="{INK}" stroke-width="4" stroke-linejoin="round"/><path d="M30 48 l-4 10 M46 48 l-4 10 M62 48 l-4 10" stroke="{INK}" stroke-width="4" stroke-linecap="round"/><path d="M28 70 a22 22 0 0 1 44 0 z" fill="var(--sk-accent)" stroke="{INK}" stroke-width="4" stroke-linejoin="round"/><path d="M50 70 v20 a5 5 0 0 0 10 0" fill="none" stroke="{INK}" stroke-width="4" stroke-linecap="round"/>', badge='sk-shield-mod', lesson='Module 3, lesson 1'),
   S('psy7', 'The signpost to the prescriber', 'The referral signpost pointing out of the clinic: medication questions go to the prescriber, and any risk goes through your risk pathway and the GP.', 'Medication questions go to the prescriber. Risk goes through your pathway and the GP.', ['recurring symbol: referral signpost', 'position: at the way out of the clinic'], 690, 100, 95, None, shared='sk-signpost', lesson='Module 4, lessons 1 and 3'),
   S('psy8', 'The myth-buster at reception', 'The myth-buster crossing out a questionnaire score: a high rating-scale score means assess properly, not that the diagnosis is made.', 'Myth: “a high scale score means ADHD.” It means assess properly.', ['recurring symbol: myth-buster', 'position: at reception, where the score arrives first'], 180, 345, 100, None, shared='sk-myth', lesson='Pitfall')]),

 # ================================================================ NUTRITION
 't-nut': dict(world='The kitchen and pantry', minutes=5, palette=('#eef3e6', '#c7d3b3', '#1c1917', '#e0a915'),
  desc='A kitchen: a bench along the back with a balance scale at its centre, two plates as separate stations on the bench, a wall clock, and a bathroom scale by the door at the right.',
  backdrop='''<rect width="800" height="450" fill="var(--sk-b1)"/><rect y="345" width="800" height="105" fill="var(--sk-b2)"/><line x1="0" y1="345" x2="800" y2="345" stroke="currentColor" stroke-width="3"/>
<rect x="20" y="262" width="600" height="18" rx="4" fill="#fdfbf7" stroke="currentColor" stroke-width="3"/><rect x="20" y="280" width="600" height="68" fill="var(--sk-b2)" stroke="currentColor" stroke-width="3"/>
<line x1="220" y1="280" x2="220" y2="348" stroke="currentColor" stroke-width="3"/><line x1="420" y1="280" x2="420" y2="348" stroke="currentColor" stroke-width="3"/>
<rect x="660" y="110" width="120" height="238" rx="6" fill="#fdfbf7" stroke="currentColor" stroke-width="3"/><circle cx="680" cy="236" r="6" fill="currentColor"/>''',
  symbols=[
   S('nut1', 'The scale: a small fish against a big pill', 'A balance scale with a small fish rising on one side and a large pill weighing down the other: omega-3 has at best a small effect, far below medication.', 'Omega-3: a small effect at best, far below medication. An addition, never a substitute.', ['action: the scale physically tips, showing the size difference', 'position: centre of the bench, the centre of the argument'], 255, 110, 150,
     f'<path d="M50 18 v64 M30 88 h40" stroke="{INK}" stroke-width="5" stroke-linecap="round"/><path d="M14 26 L86 40" stroke="{INK}" stroke-width="5" stroke-linecap="round"/><path d="M14 26 l-10 22 h20 z M86 40 l-12 26 h24 z" fill="#fdfbf7" stroke="{INK}" stroke-width="3" stroke-linejoin="round"/><path d="M6 40 q8 -7 16 0 q-8 7 -16 0 z M22 40 l5 -4 v8 z" fill="var(--sk-accent)" stroke="{INK}" stroke-width="2"/><rect x="72" y="50" width="28" height="14" rx="7" fill="var(--sk-accent)" stroke="{INK}" stroke-width="3"/><line x1="86" y1="50" x2="86" y2="64" stroke="{INK}" stroke-width="3"/>', badge='sk-shield-low', lesson='Module 3, lesson 1'),
   S('nut2', 'Breakfast first, bottle second', 'A breakfast plate placed to the left of a pill bottle under a rising sun: eat a proper breakfast before the morning dose takes effect.', 'Eat before the dose: a substantial breakfast with protein, then the medication.', ['position: the plate comes before the bottle, left to right', 'colour: accent sunrise marks the time of day'], 40, 150, 110,
     f'<path d="M10 40 a24 24 0 0 1 48 0 z" fill="var(--sk-accent)" stroke="{INK}" stroke-width="3"/><ellipse cx="34" cy="70" rx="28" ry="12" fill="#fdfbf7" stroke="{INK}" stroke-width="4"/><circle cx="28" cy="68" r="7" fill="var(--sk-accent)"/><path d="M38 66 h14" stroke="{INK}" stroke-width="5" stroke-linecap="round"/><rect x="70" y="48" width="22" height="40" rx="5" fill="#fdfbf7" stroke="{INK}" stroke-width="4"/><rect x="68" y="40" width="26" height="10" rx="3" fill="{INK}"/><path d="M56 70 h10 m-4 -4 l4 4 l-4 4" fill="none" stroke="{INK}" stroke-width="3" stroke-linecap="round"/>', lesson='Module 2, lesson 1'),
   S('nut3', 'The clock with a fork for a hand', 'A wall clock whose hand is a fork, with an alarm bell on top: when hunger cues are absent, eat by the clock.', 'No appetite at midday? Eat by the clock: alarms, and small energy-dense food.', ['wordplay made visual: the fork is the clock hand', 'position: on the wall above the bench'], 470, 60, 95,
     f'<circle cx="50" cy="56" r="36" fill="#fdfbf7" stroke="{INK}" stroke-width="5"/><path d="M50 56 V30 M44 24 v10 M50 24 v10 M56 24 v10" stroke="var(--sk-accent)" stroke-width="4" stroke-linecap="round"/><path d="M50 56 l16 10" stroke="{INK}" stroke-width="5" stroke-linecap="round"/><path d="M34 16 a16 10 0 0 1 32 0" fill="none" stroke="{INK}" stroke-width="5" stroke-linecap="round"/>', lesson='Module 2, lesson 2'),
   S('nut4', 'The varied plate', 'A plate divided into several different foods, sitting at its own station: regular, varied, adequate eating is the priority, and any link between eating pattern and ADHD is observational.', 'Priority: regular, varied, adequate meals. Links between diet pattern and ADHD are observational only.', ['position: its own station on the left of the bench', 'colour: accent segments show variety'], 425, 165, 100,
     f'<circle cx="50" cy="52" r="40" fill="#fdfbf7" stroke="{INK}" stroke-width="5"/><path d="M50 52 L50 16 A36 36 0 0 1 84 40 Z" fill="var(--sk-accent)"/><path d="M50 52 L84 40 A36 36 0 0 1 66 84 Z" fill="var(--sk-b2)"/><path d="M50 52 L66 84 A36 36 0 0 1 18 66 Z" fill="var(--sk-accent)" opacity=".55"/><path d="M50 52 L18 66 A36 36 0 0 1 50 16 Z" fill="{INK}" opacity=".25"/><circle cx="50" cy="52" r="36" fill="none" stroke="{INK}" stroke-width="2"/>', badge='sk-shield-vlow', lesson='Module 2, lesson 3'),
   S('nut5', 'The beige plate with a sugar cube', 'A plain single-colour plate with a sugar cube on it, at the opposite station: a less varied pattern is only an observational association, and sugar has not been shown to cause ADHD.', 'A “Western” pattern is an association, not a cause. Sugar has not been shown to cause ADHD.', ['position: the opposite station from the varied plate', 'colour: one flat colour, no accent'], 535, 165, 100,
     f'<circle cx="50" cy="52" r="40" fill="#fdfbf7" stroke="{INK}" stroke-width="5"/><circle cx="50" cy="52" r="30" fill="var(--sk-b2)"/><rect x="40" y="42" width="20" height="20" rx="3" fill="#fdfbf7" stroke="{INK}" stroke-width="3"/><path d="M40 48 h20 M46 42 v20" stroke="{INK}" stroke-width="1.5"/>', badge='sk-shield-vlow', lesson='Module 3, lesson 2'),
   S('nut6', 'The bathroom scale with a minus five flag', 'A bathroom scale by the door flying a small flag marked minus five per cent: unintended loss of about five per cent in three months means tell the GP.', 'Weigh regularly. Unintended loss of about 5% in three months: tell the GP.', ['colour: accent warning flag', 'proximity: beside the door and the referral signpost'], 640, 350, 95,
     f'<rect x="10" y="50" width="70" height="38" rx="10" fill="#fdfbf7" stroke="{INK}" stroke-width="4"/><path d="M28 66 a17 17 0 0 1 34 0" fill="none" stroke="{INK}" stroke-width="4"/><path d="M45 66 l8 -10" stroke="{INK}" stroke-width="4" stroke-linecap="round"/><path d="M82 50 V8" stroke="{INK}" stroke-width="4" stroke-linecap="round"/><path d="M82 8 h-42 l8 11 l-8 11 h42 z" fill="var(--sk-accent)" stroke="{INK}" stroke-width="3" stroke-linejoin="round"/><text x="62" y="25" text-anchor="middle" {F} font-size="14" fill="{INK}">−5%</text>', lesson='Module 1, lesson 2'),
   S('nut7', 'The signpost at the kitchen door', 'The referral signpost at the door: two or more positive SCOFF answers, or anything beyond general advice, goes to an Accredited Practising Dietitian and the GP.', 'SCOFF 2 or more, or medical nutrition therapy: refer to a dietitian and the GP.', ['recurring symbol: referral signpost', 'position: at the door, the way out of your scope'], 675, 125, 95, None, shared='sk-signpost', lesson='Module 1, lesson 3'),
   S('nut8', 'The myth-buster in the pantry', 'The myth-buster crossing out a sugar cube: sugar does not cause ADHD, and no diet or supplement reverses it.', 'Myth: “sugar causes ADHD” and “this supplement reverses it.” Neither is supported.', ['recurring symbol: myth-buster', 'position: in the pantry, where the claims are stored'], 140, 345, 100, None, shared='sk-myth', lesson='Pitfall')]),
}

for k, sc in SCENES.items():
    assert len(sc['symbols']) <= 8, (k, 'coherence cap is 8 symbols')
    assert len(sc['palette']) == 4, (k, '3 base colours + 1 accent')
    for sy in sc['symbols']:
        assert len(sy['cues']) >= 2, (sy['id'], 'every symbol needs at least two encoding cues')
